V2 aatish
TechAtNYU/techatnyu.org-2018 pull request #12
Opened 2017-10-25 01:25 UTC by aatish17varma

Worked on Job Page

2017-10-25 02:01 UTC, aatish17varma commented
Added Expire Date

2017-10-25 04:12 UTC, ashleytqy commented
@aatish17varma change base branch from: `TechAtNYU:ash.v2-cal` to `TechAtNYU:v2`

2017-10-25 04:24 UTC, ashleytqy commented on src/Jobs.js
> +import {IndexLink} from "react-router";
let's stick to having spaces when we deconstruct `{ IndexLink }`

2017-10-25 04:31 UTC, ashleytqy commented on src/Jobs.js
> +                    {<RaisedButton onClick = {() => {this.setState({modalIsOpen: true})}} label = "Apply" primary = {true} fullWidth = {true} />}
separate the attributes into new lines for readibility
```
<RaisedButton
  onClick = {() => {this.setState({modalIsOpen: true})}}
  label = "Apply"
  primary = {true}
  fullWidth = {true} />
```

2017-10-25 04:31 UTC, ashleytqy commented on src/Jobs.js
> +        <Modal
indentation

2017-11-11 21:15 UTC, ashleytqy commented on src/Jobs.js
> +            customStyles: {
css should be in a separate file

2017-11-13 18:39 UTC, ashleytqy commented on src/Jobs.js
> +import axios from "axios"
don't think you need to use `axios`, native `fetch` would do just fine

2017-11-19 18:31 UTC, brentdur commented on src/Jobs.js
> +const jobsURL = 'https://api.tnyu.org/v3/jobs'
Can load from `v3-test` if that helps with testing

2017-11-19 18:31 UTC, brentdur commented on src/Jobs.js
> +                    }) : console.log("")}
`console.log`?

2017-11-19 18:31 UTC, brentdur commented
Please don't commit `package-lock.json`. Add it to `.gitignore`

2018-02-04 00:39 UTC, aatish17varma commented
<img width="1280" alt="screen shot 2018-02-03 at 7 37 41 pm" src="https://user-images.githubusercontent.com/13193277/35773225-cd671bd0-0919-11e8-802a-b21432521af4.png">
<img width="1280" alt="screen shot 2018-02-03 at 7 37 29 pm" src="https://user-images.githubusercontent.com/13193277/35773226-cd6ffd54-0919-11e8-9ded-a6037c767293.png">

Gotta work on:
- Adding CSS to the buttons in the modal

2018-04-12 19:04 UTC, ashleytqy commented
You should also change the title to something more specific, like – Jobs Page, and in the description, add the url to the issue you are fixing. @aatish17varma

2018-04-12 23:27 UTC, ashleytqy commented on src/main.js
> +<MuiThemeProvider>
can you remove this?

2018-04-12 23:32 UTC, ashleytqy requested changes

2018-04-12 23:32 UTC, ashleytqy commented on src/main.js
> +<MuiThemeProvider>
can you remove this?

2018-04-12 23:32 UTC, ashleytqy commented on stylesheets/index.scss
> +
extra lines

2018-04-12 23:32 UTC, ashleytqy commented on src/Jobs.js
> +                console.log('responseData', responseData)
remove `console.log`s

2018-04-12 23:32 UTC, ashleytqy commented on src/Jobs.js
> +              )
remove commented code

2018-04-12 23:32 UTC, ashleytqy commented on src/Jobs.js
> +              { this.state.modalIsOpen == true ?
`this.state.modalIsOpen == true` => `this.state.modalIsOpen?`

2018-04-12 23:32 UTC, ashleytqy commented on package.json
> +    "axios": "^0.17.0",
remove unused package

2018-04-12 23:32 UTC, ashleytqy commented on package.json
> +    "material-ui": "^0.19.4",
remove unused package

2018-04-12 23:32 UTC, ashleytqy commented on package.json
> +    "react-modal": "^3.0.4",
remove unused package

2018-04-12 23:32 UTC, ashleytqy commented on package.json
> +    "react-router-dom": "^4.2.2",
remove unused package

2018-04-12 23:32 UTC, ashleytqy commented on src/Jobs.js
> +import Modal from "react-modal"
remove unused package

2018-04-23 22:10 UTC, merged